[package]
name = "trussed-se050-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
se05x = { version  = "0.0.1", features = ["serde"] }
trussed = { version = "0.1.0", features = ["serde-extensions"] }
trussed-auth = "0.2.2"
trussed-staging = { version = "0.1.0", features = ["wrap-key-to-file", "chunked", "encrypted-chunked"] }
delog = "0.1.6"
embedded-hal = "0.2.7"
hkdf = { version = "0.12.3", default-features = false }
sha2 = { version = "0.10.7", default-features = false }
hex-literal = "0.4.1"
serde-byte-array = "0.1.2"
iso7816 = "0.1.1"
hmac = "0.12.1"
serde = { version = "1.0.185", default-features = false, features = ["derive"] }
rand = { version = "0.8.5", default-features = false }

[patch.crates-io]
se05x = { git = "https://github.com/Nitrokey/se05x.git", rev = "5696f10dd0386b332b2e19bbbe59accdc9a647dc"} 
trussed = { git = "https://github.com/Nitrokey/trussed", tag = "v0.1.0-nitrokey.12" }
trussed-auth = { git = "https://github.com/Nitrokey/trussed-auth", rev = "e9caedb7419e80c4734db1259054cf629df6a066" }
trussed-staging = { git = "https://github.com/Nitrokey/trussed-staging.git", branch = "hmacsha256p256" }
iso7816 = { git = "https://github.com/sosthene-nitrokey/iso7816.git", rev = "160ca3bbd8e21ec4e4ee1e0748e1eaa53a45c97f"}

[features]

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []
