[package]
name = "trussed-se050-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
se05x = { version  = "0.0.1", features = ["serde", "builder"] }
trussed = { version = "0.1.0", features = ["serde-extensions"] }
trussed-auth = "0.2.2"
trussed-staging = { version = "0.1.0", features = ["wrap-key-to-file", "manage"] }
delog = "0.1.6"
embedded-hal = "0.2.7"
hkdf = { version = "0.12.3", default-features = false }
sha2 = { version = "0.10.7", default-features = false }
hex-literal = "0.4.1"
serde-byte-array = "0.1.2"
iso7816 = "0.1.1"
hmac = "0.12.1"
serde = { version = "1.0.185", default-features = false, features = ["derive"] }
rand = { version = "0.8.5", default-features = false }
littlefs2 = "0.4.0"
cbor-smol = "0.4.0"
serde_bytes = { version = "0.11.12", default-features = false }
trussed-rsa-alloc = { git = "https://github.com/Nitrokey/trussed-rsa-backend.git", rev = "2088e2f8a8d706276c1559717b4c6b6d4f270253" }
postcard = "0.7.3"
crypto-bigint = { version = "0.5.3", default-features = false }
p256 = { version = "0.13.2", default-features = false, features = ["ecdsa-core"] }
salty = "0.3.0"
p256-cortex-m4 = { version = "0.1.0-alpha.6", features = ["prehash", "sec1-signatures"] }

[patch.crates-io]
se05x = { git = "https://github.com/Nitrokey/se05x.git", rev = "d09a451246a97446f18f61b58d2b3e569b0e58f3"} 
trussed = { git = "https://github.com/Nitrokey/trussed", rev = "6b9a43fbaaf34fe8d69fac0021f8130dd9a436c9" }
trussed-auth = { git = "https://github.com/Nitrokey/trussed-auth", rev = "49c13eae6d9a225676191d4776d514848e4eab5b" }
trussed-staging = { git = "https://github.com/nitrokey/trussed-staging.git", rev = "59dda984e42fbbbd9b469c773af08b497b913469" }
iso7816 = { git = "https://github.com/sosthene-nitrokey/iso7816.git", rev = "82189c9ea9c4420e1e1fcdce362b710c9c7b19c5"}

[features]
default = ["log-all"]

log-all = []
log-none = []
log-info = []
log-debug = []
log-warn = []
log-error = []
